# Generated by Django 5.1.1 on 2025-12-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='created_at',
            new_name='created',
        ),
    ]
