# Generated by Django 5.1.1 on 2026-01-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_content_note_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='note',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
